### ISSUE TITLE
How do i change the bot's status?

### ISSUE THREAD

**Issue by InspireVortex** [navaneethkm004/Music-Bot-With-Filters-v1#2]

**Comment by navaneethkm004** [comment]
I updated the `index.js`. For changing the status, just edit this line in `index.js`
`client.user.setActivity(`${PREFIX}help | ${client.guilds.cache.size} Server`, { type: "STREAMING",
      url: "https://www.twitch.tv/nocopyrightsounds"});`.
Just edit this line with the settings you want to set
